kind: Service
apiVersion: v1
metadata:
  name: node-subscriber
  labels:
    app: node
spec:
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-ws
  labels:
    app: node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "node-subscriber"
        dapr.io/app-port: "9000"
        dapr.io/log-level: "debug"
        dapr.io/enable-api-logging: "true"
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: bff-ws
        image: testing86.azurecr.io/services/bff-ws:45fbd771a419180beb7732cdc734f072c3405a78
        env:
        - name: APP_PORT
          value: "9000"
        ports:
        - containerPort: 9000
        imagePullPolicy: Always
