name: Build and update container image for bff-ws

on:
   push:
    branches: [dev, websockets]
    paths:
      - 'backend/**'
      
permissions:
  contents: write
  pull-requests: write


jobs:

  check_changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.check_changes.outputs.matrix}}
    strategy:
      matrix:
        dir:
          - 'backend/bff-ws'
          - 'backend/bff-ws2'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Check changes in directory
      id: check_changes
      run: |
        if [[ -n $(git diff --name-only ${{ matrix.dir }}) ]]; then
          echo "::set-output name=changes::true"
        else
          echo "::set-output name=changes::false"
        fi


  build:
    needs: check_changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - 'backend/bff-ws'
          - 'backend/bff-ws2' 
    
    steps:
    - uses: actions/checkout@master

    - name: Navigate to specific Directory
      run: cd ${{ matrix.dir }}

    - uses: azure/docker-login@v1
      with:
        login-server: 'testing86.azurecr.io' # default: index.docker.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Extract last part of the directory path
      id: extract_last_part
      run: echo "::set-output name=last_part::$(basename $PWD)"

    - name: Build and push docker image
      run: |
        last_part=${{ steps.extract_last_part.outputs.last_part }}
        echo $last_part
        docker build ${{ matrix.dir}} -t testing86.azurecr.io/services/$last_part:${{ github.sha }} 
        docker push testing86.azurecr.io/services/$last_part:${{ github.sha }}

    - name: Update YAML file
      run: |
        last_part=${{ steps.extract_last_part.outputs.last_part }}
        echo $last_part
        echo "Updating YAML file in deploy directory..."
        sed -i "s|image: testing86.azurecr.io/services/$last_part:.*|image: testing86.azurecr.io/services/$last_part:${{ github.sha }}|" deploy/$last_part

    # - name: Push changes to current branch
    #   run: |
    #     git config --global user.email "actions@github.com"
    #     git config --global user.name "GitHub Actions"
    #     git add deploy/bff-ws.yaml
    #     git commit -m "Update bff-ws deployment image tag to ${{github.sha}}"
    #     git push

  commit_and_push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add backend
        git commit -m "Updated deployment image tags"
        git push
